name: 'Run tests'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add debug symbols
      run: |
        echo "deb http://ddebs.ubuntu.com $(lsb_release -cs) main restricted universe multiverse
        deb http://ddebs.ubuntu.com $(lsb_release -cs)-updates main restricted universe multiverse
        deb http://ddebs.ubuntu.com $(lsb_release -cs)-proposed main restricted universe multiverse" | \
        sudo tee -a /etc/apt/sources.list.d/ddebs.list && \
        sudo apt install ubuntu-dbgsym-keyring && \
        sudo apt update
    - name: Install dependencies
      run: sudo apt install python3 python3-pytest libwayland-dev libwayland-server0-dbgsym libwayland-client0-dbgsym gdb meson ninja-build
    - name: Run tests
      run: pytest-3
      timeout-minutes: 5
