name: 'Run tests'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: >-
        sudo apt update &&
        sudo apt install
        python3 python3-pytest mypy
        libwayland-dev wayland-protocols
        gdb meson ninja-build
    - name: Get debug libwayland
      run: >-
        cd resources &&
        git clone https://gitlab.freedesktop.org/wayland/wayland.git &&
        git checkout "$(apt search '^libwayland-client0$' | grep -Po '\d+\.\d+\.\d+')" &&
        cd wayland &&
        meson --buildtype=debug build &&
        ninja -C build
    - name: Run tests
      run: pytest-3
      timeout-minutes: 5
