name: 'Run tests'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: >-
        sudo apt update &&
        sudo apt install
        python3 python3-pytest mypy
        libwayland-dev wayland-protocols
        libwayland-server0-dbgsym libwayland-client0-dbgsym
        gdb meson ninja-build
    - name: Get debug libwayland
      run: >-
        resources/get-libwayland.sh
    - name: Run tests
      run: pytest-3
      timeout-minutes: 5
